# Generated by Django 5.2.9 on 2025-12-31 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_core.district'),
        ),
    ]
