# Generated by Django 5.2.9 on 2026-01-06 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('location_url', models.CharField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('status', models.CharField()),
                ('price', models.CharField()),
                ('description', models.CharField()),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_core.category')),
            ],
        ),
    ]
