# Generated by Django 5.2.9 on 2026-01-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(),
        ),
    ]
