# Generated by Django 5.2.9 on 2026-01-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approval_status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'acceped'), ('rejected', 'rejected')], default='pending', verbose_name='Approval_Status'),
        ),
    ]
