# Generated by Django 5.2.9 on 2026-01-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_property_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='approval_status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'acceped'), ('rejected', 'rejected')], default='requested', verbose_name='Approval_Status'),
        ),
    ]
