# Generated by Django 5.2.9 on 2026-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0011_remove_property_img_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField()),
                ('status', models.CharField()),
                ('enq_date', models.CharField()),
            ],
        ),
    ]
