# Generated by Django 5.2.9 on 2026-01-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0012_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
