# Generated by Django 5.2.9 on 2026-02-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0015_property_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
