# Generated by Django 5.2.9 on 2026-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0016_property_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('approved', 'Approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
