# Generated by Django 5.2.9 on 2026-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0018_property_registrar_status_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='doc',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
