# Generated by Django 5.2.9 on 2026-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0019_alter_property_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='doc',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
