# Generated by Django 5.2.9 on 2026-02-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0020_alter_property_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='doc',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app_core.property')),
            ],
        ),
    ]
