# Generated by Django 5.2.9 on 2026-02-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0022_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
