# Generated by Django 5.2.9 on 2026-01-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='requested'),
        ),
    ]
