# Generated by Django 5.2.9 on 2026-01-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
