# Generated by Django 5.2.9 on 2026-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller'), ('both', 'both'), ('admin', 'admin')], default='buyer', verbose_name='Role'),
        ),
    ]
