# Generated by Django 5.2.9 on 2026-02-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller'), ('both', 'both'), ('admin', 'admin'), ('registrar', 'registrar')], default='admin', verbose_name='Role'),
        ),
    ]
